language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - python setup.py build
  - sudo apt-get update -qq
  - sudo apt-get install -qq zsh
  - sudo pip install pyyaml vcstools nose-cov
  - sudo pip install coverage
# Set git config to silence some stuff in the tests
  - git config --global user.email "foo@example.com"
  - git config --global user.name "Foo Bar"
# Set the hg user
  - echo -e "[ui]\nusername = Your Name <your@mail.com>" >> ~/.hgrc
# Set the bzr user
  - bzr whoami "Your Name <name@example.com>"
# command to run tests
script:
  - nosetests test/local --with-coverage --cover-package rosinstall
# network tests are integration tests downloading ros distros
  - nosetests test/network --with-coverage --cover-package rosinstall
notifications:
  email: false
